library(Cairo)
Cairo.capabilities()
x <- rnorm(1000)
y <- rnorm(1000)
png(file = "../pics/plot.png", width = 640, height = 640)
plot(x, y)
dev.off()
CairoPNG(file = "../pics/Cairo_plot.png", width = 640, height = 640)
plot(x, y)
dev.off()
svg(file = "../pics/plot.svg", width = 6, height = 6)
plot(x, y)
dev.off()
CairoSVG(file = "../pics/Cairo_plot.svg", width = 6, height = 6)
plot(x, y)
dev.off()

