library(Cairo)
Cairo.capabilities()
x <- rnorm(1000)
y <- rnorm(1000)
png(file = "../pics/plot.png")
plot(x, y)
dev.off()
CairoPNG(file = "../pics/Cairo_plot.png")
plot(x, y)
dev.off()
svg(file = "../pics/plot.svg")
plot(x, y)
dev.off()
CairoSVG(file = "../pics/Cairo_plot.svg")
plot(x, y)
dev.off()

